### ISSUE TITLE
Auto-calculate

### ISSUE THREAD

**Issue by massierick** [sboots/meetingcostcalculator#2]
I love this tool! However, I admit, at first, the user interface had me confused. Most online calculators auto-calculate as you add content to each form field. So at first, I wasn't sure how to get the cost to pop up. Play took a long time, and the +- buttons weren't intuitive (maybe add a label saying add or subtract 15 minutes). A "calculate cost" button would be awesome to have, which would then calculate the cost based on the time you input into the "Time" field. 

It almost seems if you designed the tool as an "in-meeting" tool, where you are meant to have the site open during your meeting and hit "play" when the meeting starts, a"pause" when the meetings ends. If this is the case, you've designed it perfectly! However, you might want to add that explanation at the top of the page. I think many, like myself, will assume it's like a calculator, as opposed to a "timer/calculator". 

Either way, great job on this, and my one "issue" is that it's not completely clear how it is meant to be used. Some simple labels could go a long way in making it more intuitive for the non-tech-friendly.

**Comment by sboots** [comment]
Thanks @massierick! This was definitely a major limitation of the original version. 

I've just published an update that refreshes the interface, and adds some introductory text along with a "Set time to…" option that lets you jump immediately to different pre-set time durations.

Down the road it would definitely be more user-friendly to just be able to type a time duration into the timer field, and have it interpret and calculate that. I'll keep that on the to-do list for sure!

Here's a screenshot of the updated interface, with the "Set time to…" option:
<img width="1317" alt="Screen Shot 2019-10-04 at 21 25 41" src="https://user-images.githubusercontent.com/263472/66247694-d1064f00-e6ed-11e9-81d5-dd9c5261e1e4.png">

Thanks again!
