### ISSUE TITLE
Student Pay

### ISSUE THREAD

**Issue by massierick** [sboots/meetingcostcalculator#3]
We often have students in our meetings, so it would be cool to have their pay rates in there as well. I've forked the code and when I have time I will play around and see if i can figure it out, and send a pull request if I can actually pull it off. I'm not a terribly great coder (good at HTML and CSS, WET4, and basic jquery), but would love to help out if I can (as opposed to just submitting an issue).

**Comment by sboots** [comment]
Thanks so much @massierick! I've added student rates of pay based on the information provided on the [TBS student rates of pay webpage](https://www.canada.ca/en/treasury-board-secretariat/services/pay/rates-pay/student-rates-pay.html). Those are live now on <https://meetingcostcalculator.ca>.

Only took 2.5 years! 😅 Thanks again for suggesting it!
