### ISSUE TITLE
Suggest adding PC, CH, BI, MT, RES, REM, and ENG classifications to include a ton of scientists

### ISSUE THREAD

**Issue by Smogbuster** [sboots/meetingcostcalculator#5]

**Comment by sboots** [comment]
Thanks for the suggestion @Smogbuster! I've added those based on the [TBS rates of pay website](https://www.tbs-sct.gc.ca/pubs_pol/hrpubs/coll_agre/rates-taux-eng.asp) and (in some cases) the [TBS Rates of pay for unrepresented and senior excluded employees page](https://www.canada.ca/en/treasury-board-secretariat/services/pay/rates-pay/rates-pay-unrepresented-senior-excluded-employees.html).

You can see the full list in the [updated data repository](https://github.com/meetingcostcalculator/meeting-cost-calculator-data/blob/master/ca/rates/core.csv), effective September 2019. If I've missed any classifications, don't hesitate to give a shout!

Thanks again for flagging these!
